# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Authen-Users
version:      0.11
version_from: lib/Authen/Users.pm
installdirs:  site
requires:
    DBI:                           0
    Digest::SHA:                   0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
