--- #YAML:1.0
name:                Authen-Users
version:             0.14
abstract:            DBI/SQL based password authentication.
license:             perl
author:              
    - William Hererra (whererra@skylightview.com)
generated_by:        ExtUtils::MakeMaker version 6.42_01
distribution_type:   module
requires:     
    DBI:                           0
    Digest::SHA:                   0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
